Alec - Added PUT (edit) functionality to Students
ucsb-cs156-f24/proj-happycows-f24-09 pull request #43
Opened 2024-11-22 03:12 UTC by alecsong222

## Overview

This PR adds the Edit functionality to Students.

## Screenshots (Optional)

![image](https://github.com/user-attachments/assets/9d2b0e11-3997-4584-93e4-28afe307a45d)

## Validation (Optional)

Navigate to https://happycows-dev-alecsong222-students.dokku-09.cs.ucsb.edu/
Create a student
Navigate to PUT and Execute without filling in the id; ensure the following error shows up
![image](https://github.com/user-attachments/assets/7f4e8293-e114-4877-930d-4502d852940d)
Input your created student's ID, make edits, and ensure that the student has been edited
Use List all Students or Get a single Student by ID to ensure that your edits have been confirmed

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #0

2024-11-22 04:41 UTC, TomShangguan submitted a review, later dismissed
LGTM! I looked and tried in dokku. It works.

2024-11-24 20:51 UTC, pconrad requested changes
A few permission changes, and the unrelated code from PR #25

2024-11-24 20:51 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
>          {
What is this change doing in this PR?  

It should not be in this PR.

2024-11-24 20:51 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('ROLE_ADMIN')")
```

We should not be releasing lists of students to anyone other than the Admins.

2024-11-24 20:51 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('ROLE_ADMIN')")
```

Only admins need this ability; they are the ones managing course rosters.   There may be individual backend functions available to users where the Students and Course tables will be consulted, but that's different; here we are doing straight lookups, which should be ADMIN only.

2024-11-24 20:51 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
> +        student.setCourseId(incoming.getCourseId());
We shouldn't mess with the course id.  Once a student is added to a course, we should not change the course id.  If they were added to the wrong course they should be deleted from the one course and added to another one.

The reasons for that are that later functionality may depend on a student object being "immutable" from the standpoint of which course they "belong to" (including, for example, adding an "Instructor" role in between ADMIN and USER that can only work with the Courses and Commons that they themselves created.

2024-11-24 20:51 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Students.java
> +  private String fmName;
See Code Reviews on PR #37

2024-11-24 20:51 UTC, pconrad commented on src/main/resources/db/migration/changes/Students.json
> +          "author": "Alec Song",
We typically use the github id here.

2024-11-24 20:51 UTC, pconrad commented on src/main/resources/db/migration/changes/Students.json
> +                  },
See Code Reviews on PR #37

2024-11-24 20:51 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        }
We would actually want ADMIN to get a 200, and USER to get a 403

2024-11-24 20:51 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        @WithMockUser(roles = { "USER" })
```suggestion
        @WithMockUser(roles = { "ADMIN" })
```

2024-11-24 20:51 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        @WithMockUser(roles = { "USER" })
```suggestion
        @WithMockUser(roles = { "ADMIN" })
```

2024-11-24 20:51 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        @WithMockUser(roles = { "USER" })
```suggestion
        @WithMockUser(roles = { "ADMIN" })
```

2024-11-24 20:51 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        public void logged_in_user_can_get_all_Students() throws Exception {
```suggestion
        public void logged_in_admin_can_get_all_Students() throws Exception {
```

2024-11-25 00:29 UTC, alecsong222 reviewed
implemented all suggested changes

2024-11-26 05:15 UTC, pconrad approved these changes
LGTM

2024-11-26 22:13 UTC, merged