Alec - Added Delete Functionality to Students
ucsb-cs156-f24/proj-happycows-f24-09 pull request #44
Opened 2024-11-22 03:16 UTC by alecsong222

## Overview

This PR adds the ability to delete a Student to Students.

## Screenshots (Optional)

![image](https://github.com/user-attachments/assets/7f116d8a-7c2f-49f4-a98f-4275eb61e7a1)

## Validation (Optional)

Navigate to https://happycows-dev-alecsong222-students.dokku-09.cs.ucsb.edu/
Create a student
Try deleting a student without putting in an ID; ensure that the following error message shows up
![image](https://github.com/user-attachments/assets/5f604fc9-ab5d-474f-840a-079555ed1df3)
Input your created student's ID and ensure that it is deleted 
![image](https://github.com/user-attachments/assets/6bf73c33-926f-4527-a0ee-1b4f912212f5)

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #29

2024-11-22 03:58 UTC, elijahelephant approved these changes, later dismissed
Code looks good and I checked on your dokku deployment and eveything was working correctly. Good job

2024-11-22 04:45 UTC, alecsong222 commented
Dokku link already present - added to top of description and removed label

2024-11-24 20:56 UTC, pconrad requested changes
The "new" parts of this PR look fine for the most part, but it will need to be adjusted based on code reviews on some earlier PRs.

2024-11-24 20:56 UTC, pconrad commented on frontend/src/main/components/Leaderboard/LeaderboardTable.js
>          {
Unrelated to the PR; if it's not removed, it will delay merging until PR #25  is merged.

2024-11-24 20:56 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
> +    }
See feedback on PR #43 ... I won't repeat all of that here.  I'll just focus on DELETE.

2024-11-24 20:56 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/StudentsController.java
> +    }
This part looks good to me, and this is the "new code".

2024-11-24 20:56 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Students.java
> +  private String fmName;
See earlier code reviews...

2024-11-24 20:56 UTC, pconrad commented on src/main/resources/db/migration/changes/Students.json
> +                  },
See earlier code reviews.

2024-11-24 20:56 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        public void admin_can_delete_a_Students() throws Exception {
```suggestion
        public void admin_can_delete_a_student() throws Exception {
```

This sort of thing "doesn't matter" from a functionality standpoint, but in terms of projecting "professionalism" and "attention to detail" it really does.  It's the kind of things that stands out, for example, if you are doing coding as part of a job interview—which candidates take the time to name things carefully and consistently?  Which leave small typos and inconsistencies?

2024-11-24 20:56 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/StudentsControllerTests.java
> +        public void admin_tries_to_delete_non_existant_Students_and_gets_right_error_message()
See if you can adjust the name of the method to be cleaner.

2024-11-26 05:15 UTC, pconrad submitted a review, later dismissed
LGTM

2024-11-26 23:24 UTC, merged