Alec - Added Index Page for Students
ucsb-cs156-f24/proj-happycows-f24-09 pull request #54
Opened 2024-11-23 01:53 UTC by alecsong222

## Overview

This PR adds the index page frontend functionality for Students, that shows the table, all students, and the edit, delete, and create buttons.
https://happycows-dev-alecsong222-studentsindex.dokku-09.cs.ucsb.edu/
https://6736df13168fb974aceba3b7-dtnvecyudi.chromatic.com/

## Screenshots (Optional)

![image](https://github.com/user-attachments/assets/11224ec1-51f4-4688-af6e-09cf6bfba4b7)

## Validation (Optional)

Go to https://happycows-dev-alecsong222-studentsindex.dokku-09.cs.ucsb.edu/
Click on the Admin dropdown and go to Students
You should be taken to the Index page by default.
Ensure that the table shows up
Ensure that the Create button takes you to the un-implemented Create page

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #48

2024-11-27 00:12 UTC, elijahelephant commented
Merge main into your branch and then we should be good to add ready for staff.

2024-11-29 21:26 UTC, pconrad requested changes
One item to remove, and also wondering why the page isn't included in App.js and AppNavbar.js?

Unless/until it's included in App.js it can't actually be used.   We sometimes merge Form and Table components separately in order to increase the rate at which things can get merged, but Page components typically, we don't merge unless and until they are reachable by an end user.

2024-11-29 21:26 UTC, pconrad commented on frontend/build-storybook.log
> +
Please remove from PR, and consider adding to `.gitignore`.

2024-11-29 21:40 UTC, pconrad requested changes, later dismissed
https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/43/files should not have been merged without adding validation for the courseId.

Something like this:
```
        coursesRepository.findById(courseId).orElseThrow(() -> new EntityNotFoundException(Courses.class, courseId));
```

I won't revoke the points you already earned.  But I also won't merge anything else that touches CRUD operations for Student (front end or backend) unless until this fix is part of that PR.

2024-11-30 22:55 UTC, pconrad commented
I appreciate the extra work on this PR

But there are still some problems that make this NOT Ready-For-Staff

There are two different dokku links in the PR description. Which one should I test with? Please clean this up.

FWIW: I tried testing with both of them, and neither of them was consistent with the recent commits on the branch for this PR.  

You can verify this by going to the SystemInfo endpoint on Swagger, and looking at the commit hash, and comparing with what's on this page: https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/54/commits

I'm going to remove Ready-For-Staff, and replace it with FIXME-Deploy.

* Please update the PR description so that there is only one dokku link
* Make sure that that dokku link has an up-to-date commit from your branch—should be the last commit (or nearly the last commit, modulo any merges to make the branch up-to-date with main that might happen after you deploy.)
* Then remove FIXME-Deploy and replace with Ready-For-Staff

2024-12-01 21:20 UTC, alecsong222 commented
Updated Dokku link with most recent deployment and removed extra dokku link. Please use https://happycows-dev-alecsong222-students.dokku-09.cs.ucsb.edu

2024-12-02 00:16 UTC, pconrad approved these changes
LGTM!

2024-12-02 00:16 UTC, merged