Alec - Added Edit Page for students
ucsb-cs156-f24/proj-happycows-f24-09 pull request #57
Opened 2024-11-25 18:23 UTC by alecsong222

## Overview

This PR adds the Edit page frontend view to utilize the backend Edit functionality.

## Screenshots (Optional)

![image](https://github.com/user-attachments/assets/f9249a3a-a4cd-4997-a354-fb893e8e6bd0)

## Feedback Request (Optional)

Suggestions on how to handle the Course ID of a student when editing would be appreciated; since the Course ID of a student isn't allowed to be changed, I created a separate form for the edit page called StudentsEditForm.js and removed CourseID from there. If there are better approaches and/or things I could add please let me know.

## Validation (Optional)

Navigate to https://happycows-dev-alecsong222-students.dokku-09.cs.ucsb.edu and log in
Use Swagger to create a student with the backend
Go back to the home page, select Students from the Admin dropdown
You should be taken to the index page by default and see the student you just created
Edit the student you just created by clicking the Edit button in the table
Confirm that there is no "CourseID" field to be edited.
Submit your changes to your student and confirm that the changes have been saved.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #49

2024-11-25 20:01 UTC, TomShangguan approved these changes, later dismissed
LGTM! I reviewed and checked the functionality of your code on dokku. It works fine.

2024-11-27 00:09 UTC, elijahelephant submitted a review, later dismissed
As far as I can tell code doesn't have any glaring issues and dokku deployment works through my testing, approved and going to add ready for staff.

2024-11-29 21:28 UTC, pconrad requested changes
Please remove the irrelevant file, plus add this edit page into AppNavbar.js and App.js—otherwise, what's the point?

Also: we can't really test until it's integrated with the backend.

2024-11-29 21:28 UTC, pconrad commented on frontend/build-storybook.log
> +
Remove from PR and consider adding to `.gitignore`

2024-11-29 21:41 UTC, pconrad submitted a review, later dismissed
https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/43/files should not have been merged without adding validation for the courseId.

Something like this:
```
        coursesRepository.findById(courseId).orElseThrow(() -> new EntityNotFoundException(Courses.class, courseId));
```

I won't revoke the points you already earned.  But I also won't merge anything else that touches CRUD operations for Student (front end or backend) unless until this fix is part of that PR.

2024-12-02 00:18 UTC, pconrad commented on frontend/src/main/components/Students/StudentsEditForm.js
> +    // Note that even this complex regex may still need some tweaks
These comments appear to be leftover from code that was deleted.  Can we remove these?

2024-12-02 00:18 UTC, pconrad submitted a review, later dismissed
One very small change...

2024-12-03 16:41 UTC, pconrad approved these changes
LGTM

2024-12-03 16:41 UTC, merged