Alec students create page
ucsb-cs156-f24/proj-happycows-f24-09 pull request #58
Opened 2024-11-25 19:35 UTC by alecsong222

## Overview

This PR adds the Create Students frontend page to interface with the backend Create functionality.

## Screenshots (Optional)

![Generic placeholder image](https://picsum.photos/640/480)

## Validation (Optional)

Go to https://happycows-dev-alecsong222-students.dokku-09.cs.ucsb.edu and login
Click the dropdown menu for Admins and select students
Try creating a student with no fields filled; ensure the proper error messages are thrown
![image](https://github.com/user-attachments/assets/350e3135-f59e-4cc2-aa85-2e77291996d2)
Fill out the fields and create a student; ensure that the correct message shows up
![image](https://github.com/user-attachments/assets/072681db-0e77-456c-8621-0598b9ed9951)
Go back to the index page and ensure that you can view your student, and all fields are filled out correctly

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #0

## PR Checklist
- [ ] Commented code removed
- [ ] PR deals with only one concern
- [ ] PR Title is descriptive enough
- [ ] PR description details what a user/dev will notice is different
- [ ] No merge conflicts
- [ ] Deployed and linked with Dokku deployment
- [ ] New branch updated with main
- [ ] PR is linked to a branch
- [ ] PR is linked to an issue/ticket
- [ ] Linked issue is in "In Review" column on Kanban board
- [ ] PR is tagged with the Team's tag
- [ ] All test cases pass

2024-11-25 20:02 UTC, TomShangguan approved these changes, later dismissed
LGTM! I tried to create a student follow your steps and it works!
<img width="1425" alt="Screenshot 2024-11-25 at 12 02 13" src="https://github.com/user-attachments/assets/8a8b9b90-dd4e-4bb8-a9d7-f628a09f413a">

2024-11-27 00:07 UTC, elijahelephant approved these changes, later dismissed
I tested everything on dokku. Code looks decent as far as I can tell but I am not an expert in JS. Approved

2024-11-29 21:29 UTC, pconrad requested changes
Similar feedback to code review on PRs #54 and #57

2024-11-29 21:41 UTC, pconrad submitted a review, later dismissed
https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/43/files should not have been merged without adding validation for the courseId.

Something like this:
```
        coursesRepository.findById(courseId).orElseThrow(() -> new EntityNotFoundException(Courses.class, courseId));
```

I won't revoke the points you already earned.  But I also won't merge anything else that touches CRUD operations for Student (front end or backend) unless until this fix is part of that PR.

2024-12-02 00:20 UTC, pconrad commented on frontend/src/main/components/Students/StudentsEditForm.js
> +    // Note that even this complex regex may still need some tweaks
See code review on #57

2024-12-02 00:20 UTC, pconrad submitted a review, later dismissed
Same issue as on the previous PR

2024-12-03 16:43 UTC, pconrad approved these changes
LGTM

2024-12-03 16:49 UTC, merged